services:
  telegram-stremio:
    build: .
    container_name: tg_stremio  
    ports:
      - "8081:8081"
    volumes:
      - ./config.env:/app/config.env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1m"     
        max-file: "3"      